accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import password_reset_done

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$',views.loginview,name='login'),
    url(r'^logout/$',views.logoutview,name='logout'),
    url(r'^register/$', views.register, name='register' ),
    url(r'^profile/$', views.view_profile, name='profile'),
    url(r'^profile/view_all/$', views.view_all, name='view_all'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^profile/delete/$', views.delete_profile, name='delete_profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^reset_password/$',views.password_reset,name='password_reset'),
    url(r'^reset_password/done/$', password_reset_done, name='password_reset_done'),
    url(r'^password_reset/confirm/', views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^send_email/$', views.send_email,
        name='send_email'),
]

mywebappln/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import url, include
from django.contrib import admin
from accounts import views

urlpatterns = [
    url(r'^$', views.loginview),
    url(r'^admin/', admin.site.urls),
    url(r'^account/',include('accounts.urls')),
    url(r'^userprofile/$', views.UserProfileList.as_view()),
    url(r'^userprofile/(?P<pk>[0-9]+)/$',
        views.DetailsView.as_view(), name="details"),
    # custom api
    # url(r'^api/userprofile/$',views.userprofileapiview,name='userprofile_api'),
    # url(r'^api/userprofile/(?P<pk>[0-9]+)/$',views.userdetailapiview,name='userdetail_api')
]
urlpatterns = format_suffix_patterns(urlpatterns)

accounts/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100,default='')
    city = models.CharField(max_length=20,default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    is_live = models.BooleanField(default=True)
    token = models.CharField(max_length=100,default='')

    def __str__(self):
        return self.user.username

    def as_json(self):
        return{
            "description":self.description,
            "city":self.city,
            "website":self.website,
            "phone":self.phone,
            "username":self.user.username,
            "first_name":self.user.first_name,
            "last_name":self.user.last_name,
            "email":self.user.email,
        }

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile,sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from .models import UserProfile
from ckeditor.widgets import CKEditorWidget

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'password',
        )

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password',
        )

class EditUserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = (
            'description',
            'city',
            'website',
            'phone',
        )

class ResetPasswordForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)


class SetPasswordForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('password',)

class SendEmailForm(forms.Form):

    # userlist = User.objects.all()
    # choices = ()
    # for each in userlist:
    #     choices = choices + (each,)
    # user = forms.ChoiceField(widget=forms.Select,choices=choices)
    user = forms.ModelMultipleChoiceField(queryset = User.objects.all(),widget=forms.CheckboxSelectMultiple())
    subject = forms.CharField(max_length=20)
    body = forms.CharField(max_length=1000,widget=CKEditorWidget())

    class Meta:
        fields = ('user','subject','body')

accounts/views.py
import hashlib
from ast import literal_eval
# import requests
# from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.response import Response
from django.shortcuts import render, redirect, HttpResponse,get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.forms import PasswordChangeForm,AuthenticationForm
from django.contrib.auth import update_session_auth_hash,login,logout
from django.contrib.auth.decorators import login_required
from accounts.forms import RegistrationForm,EditProfileForm,EditUserProfileForm, ResetPasswordForm, SetPasswordForm, SendEmailForm
from django.core.mail import send_mail
from .models import User,UserProfile
from django.http import JsonResponse
from html2text import html2text



# class UserProfileList(generics.ListCreateAPIView):
#     queryset = UserProfile.objects.all()
#     serializer_class = UserProfileSerializer
#
#     def perform_create(self, serializer):
#         serializer.save()
#
# class DetailsView(generics.RetrieveUpdateDestroyAPIView):
#
#     queryset = UserProfile.objects.all()
#     serializer_class = UserProfileSerializer

class UserProfileList(APIView):

    def get(self,request):
        result = []
        for each in User.objects.all():
            result.append(each.userprofile.as_json())
        return JsonResponse(result,safe=False)

    def post(self,request):
        data_dict = literal_eval(request.body)
        print data_dict
        try:
            user = User.objects.create(
                username=data_dict.get('username'),
                email = data_dict.get('email'),
                first_name = data_dict.get('first_name'),
                last_name = data_dict.get('last_name'),
                password = data_dict.get('password'),
            )
        except:
            return JsonResponse({'msg': 'Invalid data'})
        try:
            user.userprofile.phone = data_dict.get('phone')
            user.userprofile.website = data_dict.get('website')
            user.userprofile.city = data_dict.get('city')
            user.userprofile.description = data_dict.get('description')
            user.userprofile.save()
        except:
            return JsonResponse({'msg1': 'User created succesfully','msg2': 'Userprofile created succesfully withe empty data', 'userid': user.id})

        return JsonResponse({'msg':'User created succesfully','userid':user.id})


class DetailsView(APIView):

    def get(self,request,pk):
        result =[]
        try:
            user = User.objects.get(pk=pk)
        except:
            return JsonResponse({"msg": "User not found"})
        result.append(user.userprofile.as_json())
        return JsonResponse(result, safe=False)

    def put(self,request,pk):
        try:
            user = User.objects.get(pk=pk)
        except:
            return JsonResponse({"msg": "User not found"})
        pass
        data_dict = literal_eval(request.body)
        edited = False
        if 'email' in data_dict.keys():
            user.email = data_dict['email']
            edited = True
        if 'first_name' in data_dict.keys():
            user.email = data_dict['first_name']
            edited = True
        if 'last_name' in data_dict.keys():
            user.email = data_dict['last_name']
            edited = True
        if 'phone' in data_dict.keys():
            user.userprofile.phone = data_dict['phone']
            edited = True
        if 'website' in data_dict.keys():
            user.userprofile.website = data_dict['website']
            edited = True
        if 'city' in data_dict.keys():
            user.userprofile.city = data_dict['city']
            edited = True
        if 'description' in data_dict.keys():
            user.userprofile.description = data_dict['description']
            edited = True
        if edited == True:
            user.save()
            user.userprofile.save()
            return JsonResponse({"msg": "User successfully modified"})
        return JsonResponse({"msg":"Invalid data"})


    def delete(self,request,pk):
        try:
            user = User.objects.get(pk=pk)
        except:
            return JsonResponse({"msg": "User not found"})
        user.delete()
        return JsonResponse({"msg":"User has been deleted"})


# @csrf_exempt
# def userprofileapiview(request):
#     result = []
#
#     if request.method == 'POST':
#         data_dict = literal_eval(request.body)
#         try:
#             user = User.objects.create(
#                 username=data_dict.get('username'),
#                 email = data_dict.get('email'),
#                 first_name = data_dict.get('first_name'),
#                 last_name = data_dict.get('last_name'),
#                 password = data_dict.get('password'),
#             )
#         except:
#             return JsonResponse({'msg': 'Invalid data'})
#         try:
#             user.userprofile.phone = data_dict.get('phone')
#             user.userprofile.website = data_dict.get('website')
#             user.userprofile.city = data_dict.get('city')
#             user.userprofile.description = data_dict.get('description')
#             user.userprofile.save()
#         except:
#             return JsonResponse({'msg1': 'User created succesfully','msg2': 'Userprofile created succesfully withe empty data', 'userid': user.id})
#
#         return JsonResponse({'msg':'User created succesfully','userid':user.id})
#
#     if request.method == 'GET':
#         for each in User.objects.all():
#             result.append(each.userprofile.as_json())
#
#         return JsonResponse(result,safe=False)
#
# @csrf_exempt
# def userdetailapiview(request,pk):
#     result = []
#     if request.method == 'GET':
#         try:
#             user = User.objects.get(pk=pk)
#         except:
#             return JsonResponse({"msg": "User not found"})
#         result.append(user.userprofile.as_json())
#         return JsonResponse(result, safe=False)
#
#     if request.method == 'DELETE':
#         try:
#             user = User.objects.get(pk=pk)
#         except:
#             return JsonResponse({"msg": "User not found"})
#         user.delete()
#         return JsonResponse({"msg":"User has been deleted"})
#
#     if request.method == 'PUT':
#         try:
#             user = User.objects.get(pk=pk)
#         except:
#             return JsonResponse({"msg": "User not found"})
#         pass
#         data_dict = literal_eval(request.body)
#         edited = False
#         if 'email' in data_dict.keys():
#             user.email = data_dict['email']
#             edited = True
#         if 'first_name' in data_dict.keys():
#             user.email = data_dict['first_name']
#             edited = True
#         if 'last_name' in data_dict.keys():
#             user.email = data_dict['last_name']
#             edited = True
#         if 'phone' in data_dict.keys():
#             user.userprofile.phone = data_dict['phone']
#             edited = True
#         if 'website' in data_dict.keys():
#             user.userprofile.website = data_dict['website']
#             edited = True
#         if 'city' in data_dict.keys():
#             user.userprofile.city = data_dict['city']
#             edited = True
#         if 'description' in data_dict.keys():
#             user.userprofile.description = data_dict['description']
#             edited = True
#         if edited == True:
#             user.save()
#             user.userprofile.save()
#             return JsonResponse({"msg": "User successfully modified"})
#         return JsonResponse({"msg":"Invalid data"})



def loginview(request):
    if request.POST:
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('/account/profile')
    form = AuthenticationForm()
    args = {"form": form}
    return render(request, 'accounts/login.html', args)

@login_required
def logoutview(request):
    logout(request)
    return render(request, 'accounts/logout.html')

@login_required
def view_all(request):
    user_list = UserProfile.objects.filter(is_live=True)
    table = {'user_list': user_list}
    return render(request,'accounts/view_all.html',table)


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account/login')
    form = RegistrationForm()
    args = {"form":form}
    return render(request,'accounts/reg_form.html',args)


@login_required
def view_profile(request):
    args = {'user':request.user}
    return render(request,'accounts/profile.html',args)


@login_required
def edit_profile(request):
    userprofile = UserProfile.objects.get(user=request.user)
    if request.method=='POST':
        userform = EditProfileForm(request.POST, instance=request.user)
        userprofileform = EditUserProfileForm(request.POST, instance=request.user.userprofile)
        if userform.is_valid() and userprofileform.is_valid():
            userform.save()
            userprofileform.save()
            return redirect('/account/profile')
    initial = {'description': userprofile.description, 'city': userprofile.city, 'website': userprofile.website,
               'phone': userprofile.phone}
    userform = EditProfileForm(instance=request.user)
    userprofileform = EditUserProfileForm(initial=initial)
    args = {
                'userform':userform,
                'userprofileform':userprofileform,
            }
    return render(request,'accounts/edit_profile.html',args)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST,user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect('/account/profile')

accounts/templates/accounts/change_password.html
{%extends 'base.html'%}
<html>
<head>
    {%block head%}
    <title>Change Passoword</title>
    {%endblock%}
</head>
<body>
{%block body%}
<div class="container">
    <h1>Change Password</h1>
    <h3>You can change your password here</h3>
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">Submit</button>
</form>
</div>
{%endblock%}
</body>
</html>

accounts/templates/accounts/delete_profile.html
{%extends 'base.html'%}
<html>
<head>
    {%block head%}
    <title>Delete</title>
    {%endblock%}
</head>
<body>
{%block body%}
<div class="container">
    <h1>Are you sure you want to delete your information {{user}}?</h1>
    <h2>You will be logged out!</h2>
    <br>
<form method="post">
    {%csrf_token%}
    <button type="submit">Submit</button>
</form>
</div>
{%endblock%}
</body>
</html>

accounts/templates/accounts/edit_profile.html
{%extends 'base.html'%}
<html>
<head>
    {%block head%}
    <title>Edit Profile</title>
    {%endblock%}
</head>
<body>
{%block body%}
<div class="container">
    <h1>Edit Profile</h1>
    <h3>You can edit profile information here</h3>
<form method="post">
    {%csrf_token%}
    {{userform.as_p}}
    {%csrf_token%}
    {{userprofileform.as_p}}
    <button type="submit">Submit</button>
</form>
</div>
{%endblock%}
</body>
</html>

accounts/templates/accounts/login.html
{%extends 'base.html'%}
{%block head%}
    <title>
        Login
    </title>
{%endblock%}
{%block body%}
<div class="container">
    <h1>Welcome!</h1>
        <p>You can login here</p>
        <h2>Login</h2>
        <form method="post">
            {%csrf_token%}
            {{form.as_p}}
            <button type="submit">login</button>
            <br>
        </form>
    <li><a href="/account/reset_password">Reset Password</a></li>
    </div>
{%endblock%}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block head%}

<title>login</title>

{% endblock%}

{% block body%}

<div class="container">
    <h1>Logged Out</h1>
    <p>You have logged out!</p>
</div>

{% endblock%}

accounts/templates/accounts/password_reset.html
{%extends 'base.html'%}
{%block head%}
    <title>
        Password Reset
    </title>
{%endblock%}
{%block body%}

    <div class="container">
    <h1>Welcome!</h1>
        Enter your email here
        <br>
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Submit</button>

    </form></div>
{%endblock%}

accounts/templates/accounts/password_reset_confirm.html
{%extends 'base.html'%}
{%block head%}
    <title>
        Password Reset
    </title>
{%endblock%}
{%block body%}

    <div class="container">
    <h1>Welcome!</h1>
        Enter your new password
        <br>
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Submit</button>

    </form></div>
{%endblock%}

accounts/templates/accounts/profile.html
{%extends 'base.html'%}
<html>
<head>
    {%block head%}
    <title>profile</title>
    {%endblock%}
</head>
<body>
{%block body%}
<div class="container">
    <h1>Profile</h1>
    <br>
    <h4>Username : {{user}}</h4>
    <h4>First Name : {{user.first_name}}</h4>
    <h4>Last Name : {{user.last_name}}</h4>
    <h4>Email : {{user.email}}</h4>
    <h4>Description : {{user.userprofile.description}}</h4>
    <h4>City : {{user.userprofile.city}}</h4>
    <h4>Website : {{user.userprofile.website}}</h4>
    <h4>Phone : {{user.userprofile.phone}}</h4>
    <br>
    <h4><a href="{% url 'accounts:edit_profile'%}">Edit</a></h4>
    <br>

</div>
{%endblock%}
</body>
</html>

accounts/templates/accounts/reg_form.html
{%extends 'base.html'%}
{%block head%}
    <title>
        Signup
    </title>
{%endblock%}
{%block body%}

    <div class="container">
    <h1>Welcome!</h1>
        You can register here

        <br>
        <h2>Register</h2>
    <form method="POST">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Signup</button>
    </form></div>
{%endblock%}

accounts/templates/accounts/send_email.html
{%extends 'base.html'%}
{% load static %}


{%block head%}
    <title>
        Send E-mail
    </title>
{%endblock%}
{%block body%}

    <div class="container">
    <h1>Welcome!</h1>
        Select user to send e-mail!
        <br>
    <form method="post">
        {%csrf_token%}
        {{form.media}}
        {{form.as_p}}
        <button type="submit">Send</button>
    </form>
        <!--<img src="{% static 'accounts/JPG.jpg' %}"/>-->
    </div>

{%endblock%}

accounts/templates/accounts/view_all.html
{% extends 'base.html' %}
{% block head%}

<title>Home</title>

{% endblock%}

{% block body%}

<div class="container">
    <h1>Userprofiles</h1>
    <br>
    <table class="table">
            <thead>
                <th>Id</th>
                <th>Username</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Description</th>
                <th>City</th>
                <th>Website</th>
                <th>Phone</th>
            </thead>
            {% for each in user_list%}
            <tr>
                <td>{{each.user.id}}</td>
                <td>{{each.user.username}}</td>
                <td>{{each.user.first_name}}</td>
                <td>{{each.user.last_name}}</td>
                <td>{{each.user.email}}</td>
                <td>{{each.description}}</td>
                <td>{{each.city}}</td>
                <td>{{each.website}}</td>
                <td>{{each.phone}}</td>
            </tr>
            {% endfor %}
        </table>
</div>

{% endblock%}